name: Run Nala Daily

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  action:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: ./
        env:
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
