name: Run Nala saucectl

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  action:
    name: Running tests
    if: ${{ contains(join(github.event.pull_request.labels.*.name, ' '), 'saucelabs-run-') }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: saucelabs/saucectl-run-action@v3
        with:
          working-directory: /tests
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          branch: ${{ github.event.pull_request.head.ref }}
          prUrl: ${{ github.event.pull_request.head.repo.html_url }}
          prOrg: ${{ github.event.pull_request.head.repo.owner.login }}
          prRepo: ${{ github.event.pull_request.head.repo.name }}
          prBranch: ${{ github.event.pull_request.head.ref }}
          prBaseBranch: ${{ github.event.pull_request.base.ref }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
          HLX_TKN: ${{ secrets.HLX_TKN }}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
